version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
    open-pull-requests-limit: 10
    labels:
      - 'dependencies'
      - 'automated'
    commit-message:
      prefix: 'chore(deps)'
    ignore:
      - dependency-name: '@types/node'
        update-types: ['version-update:semver-major']
    groups:
      npm-patch-minor:
        patterns:
          - '*'
        update-types:
          - 'minor'
          - 'patch'

  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
    labels:
      - 'dependencies'
      - 'github-actions'
      - 'automated'
    commit-message:
      prefix: 'deps(actions)'
    open-pull-requests-limit: 5
    groups:
      github-actions:
        patterns:
          - '*'
        update-types:
          - 'minor'
          - 'patch'
